language: node_js
node_js:
  - 12
cache:
  yarn: true
  directories:
  - $HOME/.cache/firebase
before_install:
  - cd app
  - cp .linguirc.travis .linguirc
  - yarn compileI18n
  - cp firebaseConfig.travis.ts firebaseConfig.ts
  - curl -sL https://firebase.tools | bash
script:
  - yarn ci