version: '3.8'
services:
  testBuild:
    image: gcr.io/mdcrosshare/prod:latest
    volumes:
      - "./serviceAccountKey.json:/app/serviceAccountKey.json"
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=./serviceAccountKey.json
      - PORT=5000
    ports:
      - "3000:5000"
  emulators:
    build:
      context: .
      target: emulators
    image: emulators
    ports:
      - 8080:8080
  jest:
    command: jest --runInBand
    depends_on:
      - emulators
    build:
      context: .
      target: jest
    image: jest
    volumes:
      - "./app:/src/app"