version: '3.8'
services:
  testBuild:
    image: builder
    volumes:
      - "./serviceAccountKey.json:/src/serviceAccountKey.json"
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=../serviceAccountKey.json
    ports:
      - "3000:3000"
    command: next start
  emulators:
    build:
      context: .
      target: emulators
    image: emulators
    ports:
      - 8080:8080
  jest:
    command: jest --runInBand
    depends_on:
      - emulators
    build:
      context: .
      target: jest
    image: jest
    volumes:
      - "./app:/src/app"